### ISSUE TITLE
install: investigate possibilities of osxc

### ISSUE THREAD

**Issue by kamilsk** [kamilsk/dotfiles#398]
**Motivation:** it looks exciting and has interesting techniques, e.g.

```yaml
---
# my mac:
roles:
  - role: dashboard
    disabled: YES
  - role: brew_package
    package_name: node
  - role: cask_package
    package_name: Minecraft
```

**Project:** https://osxc.github.io.

**To do:**

- use [tart](https://github.com/cirruslabs/tart) for integration tests, see related issue
